name:                vl
version:             0.1.0.0
github:              "yudaitnb/vl"
license:             BSD3
author:              "Yudai Tanabe"
maintainer:          "yudaitnb@gmail.com"
copyright:           "2022 Yudai Tanabe"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/yudaitnb/vl#readme>

dependencies:
- base >= 4.7 && < 5
- prettyprinter
# - haskeline
- haskell-src-exts
# - hint
- filepath
- directory
# - ghc-lib-parser
- mtl
- containers
- split
- sbv
- transformers
- haskell-names
- aeson
- bytestring
- regex-posix
- ghc-paths
- ghc
- timeit
- algebraic-graphs

library:
  source-dirs: src

default-extensions:
  - LambdaCase
  - FlexibleInstances
  - LambdaCase
  - TypeFamilies
  - TupleSections
  - DeriveFunctor

executables:
  vl-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vl

tests:
  vl-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vl
    - hspec

